# Generated by Django 3.0.7 on 2020-06-21 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=200)),
                ('cat_nicknames', models.TextField()),
                ('cat_dob', models.DateTimeField(verbose_name='Date of Birth')),
            ],
        ),
    ]
