# Generated by Django 3.0.7 on 2020-06-21 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0002_auto_20200621_1411'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cats',
            options={'verbose_name': 'Cats', 'verbose_name_plural': 'Cats'},
        ),
    ]
