# Generated by Django 3.0.7 on 2020-06-21 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0003_auto_20200621_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='cats',
            name='cat_image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
